### ISSUE TITLE
RPC bad connection broke insight

### ISSUE THREAD

**Issue by KamuelaFranco** [dashevo/insight-ui#29]
@Serrenima, due to a repository migration, this is a copy of your issue from 14 Jan 2018:

Hi all,When I try to coonect RPC with bad Port, :3001/insight is can't open page, dash core is work, because gen. address.Any ideas?Because if bad guys try to connect with my IP and incorrectly port, they down insight.Thanks

**Comment by nmarley** [comment]
Closed in original repo
